/**
 * PDF Document Styles
 *
 * Shared styles for all PDF documents generated by the system.
 */

import { StyleSheet, Font } from "@react-pdf/renderer"

// Register fonts if needed (optional - uses default Helvetica)
// Font.register({
//   family: 'Roboto',
//   src: '/fonts/Roboto-Regular.ttf',
// })

export const colors = {
  primary: "#8B2332", // Maroon (GSPN brand)
  secondary: "#6b7280", // Gray
  accent: "#D4AF37", // Gold (GSPN brand)
  success: "#16a34a", // Green
  warning: "#ca8a04", // Yellow
  danger: "#dc2626", // Red
  text: "#1f2937", // Dark gray
  textLight: "#6b7280", // Light gray
  border: "#e5e7eb", // Border gray
  background: "#f9fafb", // Light background
  white: "#ffffff",
}

export const styles = StyleSheet.create({
  // Page layout
  page: {
    flexDirection: "column",
    backgroundColor: colors.white,
    padding: 40,
    fontFamily: "Helvetica",
    fontSize: 10,
    color: colors.text,
  },

  // Header / Letterhead
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 2,
    borderBottomColor: colors.primary,
  },
  logoContainer: {
    width: 80,
    height: 80,
    justifyContent: "center",
    alignItems: "center",
  },
  logo: {
    width: 70,
    height: 70,
    objectFit: "contain",
  },
  schoolInfo: {
    flex: 1,
    alignItems: "center",
    paddingHorizontal: 20,
  },
  schoolName: {
    fontSize: 18,
    fontFamily: "Helvetica-Bold",
    color: colors.primary,
    textAlign: "center",
    marginBottom: 4,
  },
  schoolNameAr: {
    fontSize: 14,
    textAlign: "center",
    marginBottom: 4,
    color: colors.secondary,
  },
  schoolAddress: {
    fontSize: 9,
    textAlign: "center",
    color: colors.textLight,
    marginBottom: 2,
  },
  schoolContact: {
    fontSize: 9,
    textAlign: "center",
    color: colors.textLight,
  },
  headerRight: {
    width: 100,
    alignItems: "flex-end",
  },
  yearBadge: {
    backgroundColor: colors.primary,
    color: colors.white,
    padding: "4 8",
    fontSize: 9,
    borderRadius: 4,
  },

  // Document Title
  documentTitle: {
    fontSize: 16,
    fontFamily: "Helvetica-Bold",
    textAlign: "center",
    color: colors.primary,
    marginBottom: 5,
  },
  documentTitleFr: {
    fontSize: 12,
    textAlign: "center",
    color: colors.secondary,
    marginBottom: 20,
  },

  // Section
  section: {
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 12,
    fontFamily: "Helvetica-Bold",
    color: colors.primary,
    marginBottom: 8,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },

  // Info Grid (two columns)
  infoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  infoRow: {
    width: "50%",
    flexDirection: "row",
    marginBottom: 6,
    paddingRight: 10,
  },
  infoRowFull: {
    width: "100%",
    flexDirection: "row",
    marginBottom: 6,
  },
  infoLabel: {
    width: 100,
    fontSize: 9,
    color: colors.textLight,
    fontFamily: "Helvetica-Bold",
  },
  infoValue: {
    flex: 1,
    fontSize: 10,
    color: colors.text,
  },

  // Table
  table: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: colors.primary,
    color: colors.white,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  tableRowAlt: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.background,
  },
  tableCell: {
    padding: 8,
    fontSize: 9,
    flex: 1,
  },
  tableCellHeader: {
    padding: 8,
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: colors.white,
    flex: 1,
  },
  tableCellSmall: {
    padding: 8,
    fontSize: 9,
    width: 60,
  },
  tableCellMedium: {
    padding: 8,
    fontSize: 9,
    width: 100,
  },
  tableCellLarge: {
    padding: 8,
    fontSize: 9,
    flex: 2,
  },

  // Summary box
  summaryBox: {
    marginTop: 15,
    padding: 15,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 4,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 5,
  },
  summaryLabel: {
    fontSize: 10,
    color: colors.textLight,
  },
  summaryValue: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: colors.text,
  },
  summaryTotal: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  summaryTotalLabel: {
    fontSize: 12,
    fontFamily: "Helvetica-Bold",
    color: colors.primary,
  },
  summaryTotalValue: {
    fontSize: 12,
    fontFamily: "Helvetica-Bold",
    color: colors.primary,
  },

  // Status badge
  statusBadge: {
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: 4,
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    textTransform: "uppercase",
  },
  statusApproved: {
    backgroundColor: "#dcfce7",
    color: colors.success,
  },
  statusSubmitted: {
    backgroundColor: "#fef3c7",
    color: colors.warning,
  },
  statusDraft: {
    backgroundColor: "#f3f4f6",
    color: colors.secondary,
  },
  statusRejected: {
    backgroundColor: "#fee2e2",
    color: colors.danger,
  },

  // Signature section
  signatureSection: {
    marginTop: 40,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  signatureBox: {
    width: "45%",
  },
  signatureLabel: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    marginBottom: 40,
  },
  signatureLine: {
    borderTopWidth: 1,
    borderTopColor: colors.text,
    paddingTop: 5,
  },
  signatureText: {
    fontSize: 9,
    color: colors.textLight,
    textAlign: "center",
  },

  // Footer
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 10,
  },
  footerText: {
    fontSize: 8,
    color: colors.textLight,
  },
  footerPage: {
    fontSize: 8,
    color: colors.textLight,
  },

  // Utility
  bold: {
    fontFamily: "Helvetica-Bold",
  },
  italic: {
    fontFamily: "Helvetica-Oblique",
  },
  textCenter: {
    textAlign: "center",
  },
  textRight: {
    textAlign: "right",
  },
  mb10: {
    marginBottom: 10,
  },
  mb20: {
    marginBottom: 20,
  },
  mt10: {
    marginTop: 10,
  },
  mt20: {
    marginTop: 20,
  },
})
