"use client"

import { useState, useEffect, useCallback } from "react"
import {
  CreditCard,
  AlertCircle,
  Users,
  User,
  UserCircle,
  Check,
  Loader2,
  Banknote,
  Smartphone,
  Info,
} from "lucide-react"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"
import { Badge } from "@/components/ui/badge"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { cn } from "@/lib/utils"
import { sizing } from "@/lib/design-tokens"
import { useI18n } from "@/components/i18n-provider"
import { useClubEnrollmentWizard } from "../wizard-context"
import type { PayerType } from "@/lib/types/club-enrollment"

export function StepPaymentTransaction() {
  const { locale } = useI18n()
  const { state, setPayment } = useClubEnrollmentWizard()

  const [isGeneratingReceipt, setIsGeneratingReceipt] = useState(false)
  const [displayAmount, setDisplayAmount] = useState("")

  const translations = {
    recordPayment: locale === "fr" ? "Enregistrer le Paiement" : "Record Payment",
    recordPaymentDescription: locale === "fr"
      ? "Enregistrez un paiement pour cette inscription (optionnel)"
      : "Record a payment for this enrollment (optional)",
    paymentOptionalInfo: locale === "fr"
      ? "Vous pouvez enregistrer le paiement maintenant ou plus tard. Si le paiement n'est pas enregistré, l'inscription sera sauvegardée en attente de paiement."
      : "You can record payment now or later. If payment is not recorded, the enrollment will be saved as pending payment.",
    paymentAmount: locale === "fr" ? "Montant du Paiement" : "Payment Amount",
    paymentAmountHelp: locale === "fr"
      ? "Entrez le montant payé (peut être un paiement partiel)"
      : "Enter the amount being paid (can be partial payment)",
    paymentMethod: locale === "fr" ? "Mode de Paiement" : "Payment Method",
    cash: locale === "fr" ? "Espèces" : "Cash",
    orangeMoney: "Orange Money",
    receiptNumber: locale === "fr" ? "Numéro de Reçu" : "Receipt Number",
    autoGenerated: locale === "fr" ? "Généré automatiquement" : "Auto-generated",
    generating: locale === "fr" ? "Génération..." : "Generating...",
    transactionRef: locale === "fr" ? "Référence de Transaction (Optionnel)" : "Transaction Reference (Optional)",
    whoIsPaying: locale === "fr" ? "Qui effectue ce paiement ?" : "Who is making this payment?",
    payerName: locale === "fr" ? "Nom du Payeur" : "Payer Name",
    fullName: locale === "fr" ? "Nom complet" : "Full name",
    phoneNumber: locale === "fr" ? "Numéro de Téléphone" : "Phone Number",
    email: "Email",
    optional: locale === "fr" ? "optionnel" : "optional",
    notes: "Notes",
    notesPlaceholder: locale === "fr"
      ? "Ajoutez des notes supplémentaires concernant cette inscription..."
      : "Add any additional notes about this enrollment...",
    selected: locale === "fr" ? "Sélectionné" : "Selected",
    father: locale === "fr" ? "Père" : "Father",
    mother: locale === "fr" ? "Mère" : "Mother",
    enrollingPerson: locale === "fr" ? "Personne inscrivante" : "Enrolling Person",
    other: locale === "fr" ? "Autre" : "Other",
    totalOwed: locale === "fr" ? "Total dû" : "Total Owed",
  }

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat("fr-GN", {
      style: "currency",
      currency: "GNF",
      minimumFractionDigits: 0,
    }).format(amount)
  }

  const formatNumber = (value: number) => {
    return new Intl.NumberFormat("fr-FR").format(value)
  }

  // Calculate total owed from Step 3
  const totalOwed = state.data.customTotal ??
    ((state.data.enrollmentFee || 0) + (state.data.totalMonthlyFees || 0))

  // Fetch next receipt number
  const fetchReceiptNumber = useCallback(async (method: "cash" | "orange_money") => {
    setIsGeneratingReceipt(true)
    try {
      const response = await fetch(`/api/payments/next-receipt-number?method=${method}`)
      if (response.ok) {
        const data = await response.json()
        return data.receiptNumber
      }
    } catch (err) {
      console.error("Failed to fetch receipt number:", err)
    } finally {
      setIsGeneratingReceipt(false)
    }
    return null
  }, [])

  // Auto-generate receipt number when payment method changes
  useEffect(() => {
    async function generateReceipt() {
      if (
        state.data.paymentMethod &&
        state.data.paymentAmount &&
        state.data.paymentAmount > 0 &&
        !state.data.receiptNumber
      ) {
        const receiptNumber = await fetchReceiptNumber(state.data.paymentMethod)
        if (receiptNumber) {
          setPayment({ receiptNumber })
        }
      }
    }
    generateReceipt()
  }, [state.data.paymentMethod, state.data.paymentAmount, state.data.receiptNumber, fetchReceiptNumber, setPayment])

  const handlePaymentChange = (field: string, value: string | number) => {
    setPayment({ [field]: value })
  }

  const handleAmountChange = (inputValue: string) => {
    // Remove all non-digit characters
    const numericValue = inputValue.replace(/\D/g, "")
    const parsedAmount = parseInt(numericValue) || 0

    // Update the actual payment amount
    setPayment({ paymentAmount: parsedAmount })

    // Update the formatted display value
    if (numericValue) {
      setDisplayAmount(formatNumber(parsedAmount))
    } else {
      setDisplayAmount("")
    }
  }

  // Initialize display amount when payment amount changes from other sources
  useEffect(() => {
    if (state.data.paymentAmount && state.data.paymentAmount > 0 && !displayAmount) {
      setDisplayAmount(formatNumber(state.data.paymentAmount))
    }
  }, [state.data.paymentAmount])

  // Handle payment method change
  const handleMethodChange = async (method: "cash" | "orange_money") => {
    setPayment({ paymentMethod: method, receiptNumber: "" })
    const receiptNumber = await fetchReceiptNumber(method)
    if (receiptNumber) {
      setPayment({ receiptNumber })
    }
  }

  // Handle payer type selection
  const handlePayerTypeChange = (type: PayerType) => {
    let payerInfo = { type, name: "", phone: "", email: "" }

    // Pre-fill from enrollment payer info
    const enrollmentPayerInfo = state.data.enrollmentPayerInfo
    if (enrollmentPayerInfo) {
      switch (type) {
        case "father":
          payerInfo = {
            type,
            name: enrollmentPayerInfo.fatherName || "",
            phone: enrollmentPayerInfo.fatherPhone || "",
            email: enrollmentPayerInfo.fatherEmail || "",
          }
          break
        case "mother":
          payerInfo = {
            type,
            name: enrollmentPayerInfo.motherName || "",
            phone: enrollmentPayerInfo.motherPhone || "",
            email: enrollmentPayerInfo.motherEmail || "",
          }
          break
        case "enrolling_person":
          payerInfo = {
            type,
            name: enrollmentPayerInfo.enrollingPersonName || "",
            phone: enrollmentPayerInfo.enrollingPersonPhone || "",
            email: enrollmentPayerInfo.enrollingPersonEmail || "",
          }
          break
        case "other":
          payerInfo = { type, name: "", phone: "", email: "" }
          break
      }
    }

    setPayment({ payer: payerInfo })
  }

  // Get payer type options
  const payerOptions = [
    {
      value: "father" as PayerType,
      label: translations.father,
      icon: User,
      available: !!state.data.enrollmentPayerInfo?.fatherName,
      name: state.data.enrollmentPayerInfo?.fatherName,
    },
    {
      value: "mother" as PayerType,
      label: translations.mother,
      icon: UserCircle,
      available: !!state.data.enrollmentPayerInfo?.motherName,
      name: state.data.enrollmentPayerInfo?.motherName,
    },
    {
      value: "enrolling_person" as PayerType,
      label: translations.enrollingPerson,
      icon: Users,
      available: !!state.data.enrollmentPayerInfo?.enrollingPersonName,
      name: state.data.enrollmentPayerInfo?.enrollingPersonName,
    },
    {
      value: "other" as PayerType,
      label: translations.other,
      icon: User,
      available: true,
      name: null,
    },
  ]

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      {/* Header */}
      <div className="text-center space-y-2">
        <h2 className="text-2xl font-bold text-foreground">{translations.recordPayment}</h2>
        <p className="text-muted-foreground">{translations.recordPaymentDescription}</p>
      </div>

      {/* Total Owed Summary */}
      <div className="p-4 bg-gradient-to-r from-amber-50 to-orange-50 border-2 border-amber-200 rounded-xl">
        <div className="flex items-center justify-between">
          <span className="text-gray-700 font-medium">{translations.totalOwed}</span>
          <span className="text-2xl font-bold text-amber-700">{formatCurrency(totalOwed)}</span>
        </div>
      </div>

      {/* Payment Section */}
      <div className="p-6 bg-white border-2 border-border rounded-xl space-y-6">
        <div className="flex items-center gap-2">
          <CreditCard className={sizing.icon.sm} />
          <h3 className="font-bold text-lg text-foreground">{translations.recordPayment}</h3>
        </div>

        <Alert className="bg-blue-50 border-blue-200">
          <AlertCircle className={sizing.icon.sm} />
          <AlertDescription>
            {translations.paymentOptionalInfo}
          </AlertDescription>
        </Alert>

        <div className="space-y-6">
          {/* Payment Amount */}
          <div className="space-y-2">
            <Label htmlFor="paymentAmount">{translations.paymentAmount}</Label>
            <Input
              id="paymentAmount"
              type="text"
              placeholder="0"
              value={displayAmount}
              onChange={(e) => handleAmountChange(e.target.value)}
              className="min-h-[44px]"
              aria-describedby="payment-amount-help"
            />
            <p id="payment-amount-help" className="text-sm text-gray-500">
              {translations.paymentAmountHelp}
            </p>
          </div>

          {/* Payment Method */}
          {state.data.paymentAmount && state.data.paymentAmount > 0 && (
            <>
              <div className="space-y-3">
                <Label>{translations.paymentMethod}</Label>
                <RadioGroup
                  value={state.data.paymentMethod || ""}
                  onValueChange={(v) => handleMethodChange(v as "cash" | "orange_money")}
                  className="grid grid-cols-2 gap-4"
                >
                  <Label
                    htmlFor="cash"
                    className={cn(
                      "flex items-center gap-3 p-4 border-2 rounded-lg cursor-pointer transition-all",
                      state.data.paymentMethod === "cash"
                        ? "border-emerald-500 bg-emerald-50"
                        : "border-border hover:border-gray-300"
                    )}
                  >
                    <RadioGroupItem value="cash" id="cash" className="sr-only" />
                    <div className={cn(
                      "p-2.5 rounded-full",
                      state.data.paymentMethod === "cash" ? "bg-emerald-100" : "bg-gray-100"
                    )}>
                      <Banknote className={cn(
                        sizing.icon.md,
                        state.data.paymentMethod === "cash" ? "text-emerald-600" : "text-gray-500"
                      )} />
                    </div>
                    <div>
                      <span className="font-medium">{translations.cash}</span>
                      {state.data.paymentMethod === "cash" && (
                        <Check className={cn(sizing.icon.sm, "inline ml-2 text-emerald-600")} />
                      )}
                    </div>
                  </Label>

                  <Label
                    htmlFor="orange_money"
                    className={cn(
                      "flex items-center gap-3 p-4 border-2 rounded-lg cursor-pointer transition-all",
                      state.data.paymentMethod === "orange_money"
                        ? "border-orange-500 bg-orange-50"
                        : "border-border hover:border-gray-300"
                    )}
                  >
                    <RadioGroupItem value="orange_money" id="orange_money" className="sr-only" />
                    <div className={cn(
                      "p-2.5 rounded-full",
                      state.data.paymentMethod === "orange_money" ? "bg-orange-100" : "bg-gray-100"
                    )}>
                      <Smartphone className={cn(
                        sizing.icon.md,
                        state.data.paymentMethod === "orange_money" ? "text-orange-600" : "text-gray-500"
                      )} />
                    </div>
                    <div>
                      <span className="font-medium">{translations.orangeMoney}</span>
                      {state.data.paymentMethod === "orange_money" && (
                        <Check className={cn(sizing.icon.sm, "inline ml-2 text-orange-600")} />
                      )}
                    </div>
                  </Label>
                </RadioGroup>
              </div>

              {/* Receipt Number */}
              <div className="space-y-2">
                <Label htmlFor="receiptNumber">
                  {translations.receiptNumber}
                </Label>
                <div className="relative">
                  <Input
                    id="receiptNumber"
                    type="text"
                    value={state.data.receiptNumber || ""}
                    readOnly
                    placeholder={isGeneratingReceipt ? translations.generating : "GSPN-2025-CLUB-00001"}
                    className={cn(
                      "font-mono bg-muted/50 cursor-not-allowed min-h-[44px]",
                      isGeneratingReceipt && "pr-10"
                    )}
                  />
                  {isGeneratingReceipt && (
                    <Loader2 className={cn(
                      "absolute right-3 top-1/2 -translate-y-1/2 animate-spin text-gray-400",
                      sizing.icon.sm
                    )} />
                  )}
                </div>
                <div className="flex items-center gap-1 text-xs text-gray-500">
                  <Info className={sizing.icon.xs} />
                  <span>{translations.autoGenerated}</span>
                </div>
              </div>

              {/* Transaction Reference */}
              {state.data.paymentMethod === "orange_money" && (
                <div className="space-y-2">
                  <Label htmlFor="transactionRef">{translations.transactionRef}</Label>
                  <Input
                    id="transactionRef"
                    type="text"
                    placeholder="MP24010100001"
                    value={state.data.transactionRef || ""}
                    onChange={(e) => handlePaymentChange("transactionRef", e.target.value)}
                    className="min-h-[44px]"
                  />
                </div>
              )}

              {/* Payer Selection */}
              <div className="space-y-4 pt-4 border-t-2 border-border">
                <div className="flex items-center gap-2">
                  <Users className={sizing.icon.sm} />
                  <Label className="text-base font-semibold">{translations.whoIsPaying}</Label>
                </div>

                {/* Payer Type Selection */}
                <RadioGroup
                  value={state.data.payer?.type || ""}
                  onValueChange={(v) => handlePayerTypeChange(v as PayerType)}
                  className="grid grid-cols-2 md:grid-cols-4 gap-2"
                >
                  {payerOptions.map((option) => {
                    const Icon = option.icon
                    const isSelected = state.data.payer?.type === option.value
                    return (
                      <Label
                        key={option.value}
                        htmlFor={`payer-${option.value}`}
                        className={cn(
                          "flex flex-col items-center gap-2 p-3 border-2 rounded-lg cursor-pointer transition-all text-center min-h-[44px]",
                          isSelected
                            ? "border-amber-500 bg-amber-50"
                            : "border-border hover:border-amber-300",
                          !option.available && option.value !== "other" && "opacity-50"
                        )}
                      >
                        <RadioGroupItem
                          value={option.value}
                          id={`payer-${option.value}`}
                          className="sr-only"
                        />
                        <Icon className={cn(
                          sizing.icon.md,
                          isSelected ? "text-amber-600" : "text-gray-500"
                        )} />
                        <span className="text-sm font-medium">{option.label}</span>
                        {option.name && (
                          <span className="text-xs text-gray-500 truncate max-w-full">
                            {option.name}
                          </span>
                        )}
                        {isSelected && (
                          <Badge className="text-xs bg-amber-600 hover:bg-amber-700">
                            <Check className={cn(sizing.icon.xs, "mr-1")} />
                            {translations.selected}
                          </Badge>
                        )}
                      </Label>
                    )
                  })}
                </RadioGroup>

                {/* Payer Details (editable for "other" or to override) */}
                {state.data.payer && (
                  <div className="space-y-4 pt-2">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <Label htmlFor="payerName">
                          {translations.payerName} <span className="text-red-500" aria-label="required">*</span>
                        </Label>
                        <Input
                          id="payerName"
                          value={state.data.payer.name}
                          onChange={(e) => setPayment({
                            payer: { ...state.data.payer!, name: e.target.value }
                          })}
                          placeholder={translations.fullName}
                          className="min-h-[44px]"
                          required
                        />
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="payerPhone">
                          {translations.phoneNumber} <span className="text-red-500" aria-label="required">*</span>
                        </Label>
                        <Input
                          id="payerPhone"
                          type="tel"
                          value={state.data.payer.phone}
                          onChange={(e) => setPayment({
                            payer: { ...state.data.payer!, phone: e.target.value }
                          })}
                          placeholder="+224 XXX XX XX XX"
                          className="min-h-[44px]"
                          required
                        />
                      </div>
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="payerEmail">
                        {translations.email} ({translations.optional})
                      </Label>
                      <Input
                        id="payerEmail"
                        type="email"
                        value={state.data.payer.email || ""}
                        onChange={(e) => setPayment({
                          payer: { ...state.data.payer!, email: e.target.value }
                        })}
                        placeholder="email@example.com"
                        className="min-h-[44px]"
                      />
                    </div>
                  </div>
                )}
              </div>
            </>
          )}

          {/* Notes */}
          <div className="space-y-2">
            <Label htmlFor="notes">{translations.notes} ({translations.optional})</Label>
            <Textarea
              id="notes"
              placeholder={translations.notesPlaceholder}
              value={state.data.notes || ""}
              onChange={(e) => handlePaymentChange("notes", e.target.value)}
              rows={3}
            />
          </div>
        </div>
      </div>
    </div>
  )
}
