name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '9'

jobs:
  # ============================================================================
  # JOB 1: LINT - ESLint + Prettier + Prisma Format
  # ============================================================================
  lint:
    name: Lint Code Quality
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: ESLint - app/ui
        run: cd app/ui && pnpm lint

      - name: ESLint - design-ux
        run: cd design-ux && pnpm lint

      - name: Prettier - Check formatting
        run: pnpm exec prettier --check .

      - name: Prisma - Format check
        run: cd app/db && pnpm prisma format --check

  # ============================================================================
  # JOB 2: TYPECHECK - TypeScript compilation
  # ============================================================================
  typecheck:
    name: TypeScript Type Checking
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: TypeScript - Check app/ui
        run: cd app/ui && pnpm typecheck

      - name: TypeScript - Check design-ux
        run: cd design-ux && pnpm typecheck

  # ============================================================================
  # JOB 3: SECURITY - Dependency audit + vulnerability scanning
  # ============================================================================
  security:
    name: Security Scanning
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Audit dependencies
        run: pnpm audit --audit-level=moderate
        continue-on-error: true

      - name: Snyk security scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
        if: secrets.SNYK_TOKEN != ''

  # ============================================================================
  # JOB 4: BUILD - Next.js production builds
  # ============================================================================
  build:
    name: Build Projects
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        workspace: [app/ui, design-ux]
        node-version: ['20']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build ${{ matrix.workspace }}
        run: cd ${{ matrix.workspace }} && pnpm build
        env:
          NEXTAUTH_SECRET: test-secret-key-for-ci-only
          NEXTAUTH_URL: http://localhost:3000
          NEXT_PUBLIC_ENVIRONMENT: ci

      - name: Check build output
        run: |
          if [ -d "${{ matrix.workspace }}/.next" ]; then
            echo "✅ Build output verified"
            du -sh ${{ matrix.workspace }}/.next
          else
            echo "❌ Build output not found"
            exit 1
          fi

      - name: Upload build artifacts
        if: matrix.workspace == 'app/ui'
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.workspace }}
          path: ${{ matrix.workspace }}/.next
          retention-days: 1

  # ============================================================================
  # JOB 5: TESTS - Unit tests and coverage
  # ============================================================================
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test:run
        continue-on-error: true

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            app/ui/coverage
            design-ux/coverage
          retention-days: 5

      - name: Comment PR with coverage
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '📊 Test coverage reports uploaded as artifacts'
            })
        continue-on-error: true

  # ============================================================================
  # JOB 6: DATABASE - Prisma schema validation
  # ============================================================================
  database:
    name: Database Schema Validation
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Validate Prisma schema
        run: cd app/db && pnpm prisma validate

      - name: Format check Prisma schema
        run: cd app/db && pnpm prisma format --check

      - name: Check for migration drift
        run: cd app/db && pnpm prisma migrate status || echo "⚠️ Database not initialized (expected in CI)"
        continue-on-error: true

  # ============================================================================
  # JOB 7: DOCUMENTATION - Markdown validation
  # ============================================================================
  documentation:
    name: Documentation Validation
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Markdown lint
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: docs/
          config_file: .markdownlint.json
        continue-on-error: true

      - name: Check for broken links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          folder-path: docs/
        continue-on-error: true

  # ============================================================================
  # JOB 8: E2E TESTS - Playwright integration tests (optional)
  # ============================================================================
  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: cd app/ui && pnpm exec playwright install --with-deps
        continue-on-error: true

      - name: Run E2E tests
        run: cd app/ui && pnpm test:e2e
        env:
          NEXTAUTH_SECRET: test-secret-key-for-ci-only
          NEXTAUTH_URL: http://localhost:3000
        continue-on-error: true

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: app/ui/playwright-report/
          retention-days: 5

  # ============================================================================
  # JOB 9: STATUS CHECK - Final gate for all critical checks
  # ============================================================================
  status-check:
    name: CI Status Gate
    runs-on: ubuntu-latest
    needs: [lint, typecheck, security, build, database]
    if: always()
    timeout-minutes: 5

    steps:
      - name: Check critical job statuses
        run: |
          echo "🔍 Checking CI job statuses..."
          echo ""

          # Define job status check function
          check_status() {
            local job_name=$1
            local job_result=$2
            
            if [ "$job_result" = "success" ]; then
              echo "✅ $job_name: PASSED"
              return 0
            else
              echo "❌ $job_name: FAILED"
              return 1
            fi
          }

          # Check each critical job
          FAILED=0
          check_status "Lint" "${{ needs.lint.result }}" || FAILED=1
          check_status "TypeCheck" "${{ needs.typecheck.result }}" || FAILED=1
          check_status "Security" "${{ needs.security.result }}" || FAILED=1
          check_status "Build" "${{ needs.build.result }}" || FAILED=1
          check_status "Database" "${{ needs.database.result }}" || FAILED=1

          echo ""
          if [ $FAILED -eq 1 ]; then
            echo "❌ CI Pipeline FAILED - Some checks did not pass"
            exit 1
          else
            echo "✅ CI Pipeline PASSED - All critical checks passed"
            exit 0
          fi

      - name: Comment PR on success
        if: success() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ All CI checks passed! This PR is ready for review.'
            })
        continue-on-error: true

      - name: Comment PR on failure
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ CI checks failed. Please review the logs and fix the issues.'
            })
        continue-on-error: true
